# -*- coding: utf-8 -*-
"""스켈레톤.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Am5oRVWrgWwAaNbynhfaDDZZB4SLK4iW
"""

# 사용자 관절 데이터 확인 

import numpy as np
import matplotlib.pyplot as plt

# ---------------------------
# 1. 사용자 관절 데이터
# ---------------------------
coords = np.array([
    [0.6300804, 0.3862279, -0.1800956],  # 0 left shoulder
    [0.4410107, 0.3599773, -0.1550435],  # 1 right shoulder

    [0.5893860, 0.4558804, -0.3774264],  # 2 left elbow
    [0.3353628, 0.4086872, -0.4049845],  # 3 right elbow

    [0.5149344, 0.4169530, -0.7744084],  # 4 left wrist
    [0.3939202, 0.3853071, -0.8478600],  # 5 right wrist

    [0.5569154, 0.5336347, -0.0010835],  # 6 left hip
    [0.4362963, 0.5337196, 0.0008508],   # 7 right hip

    [0.6532460, 0.6436756, -0.0020700],  # 8 left knee
    [0.3949564, 0.6579794, -0.0496367],  # 9 right knee

    [0.7307456, 0.7352291, 0.4672561],   # 10 left ankle
    [0.3446633, 0.7684151, 0.3005700],   # 11 right ankle
])

# ---------------------------
# 2. 연결 정의
# ---------------------------
EDGES = [
    (0,2), (2,4),   # left arm
    (1,3), (3,5),   # right arm
    (0,1),          # shoulders
    (6,7),          # hips
    (0,6), (1,7),   # torso
    (6,8), (8,10),  # left leg
    (7,9), (9,11),  # right leg
]

# ---------------------------
# 3. matplotlib 3D plot
# ---------------------------
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

for i, j in EDGES:
    ax.plot(
        [coords[i,0], coords[j,0]],   # x
        # y,z 뒤집는 이유: 미디어파이프는 y를 높이로 보지만 스켈레톤의 경우 z를 높이로 본다. 그래서 바꿔야 함
        [coords[i,2], coords[j,2]],   # z → y
        # z에 -인 이유: y의 경우 미디어파이프는 아래로 갈수록 증가함 그런데 좌표의 경우 y는 위로 갈수록 증가하기 때문에 제대로 볼려면 뒤집어야 함
        [-coords[i,1], -coords[j,1]]    # y 뒤집기
    )

ax.scatter(
    coords[:,0],
    coords[:,2],
    -coords[:,1]
)

# 원점을 빨간 점으로 표시
ax.scatter(0, 0, 0, color='red', s=100, label='Origin')

ax.set_xlabel('X (left-right)')
ax.set_ylabel('Z (depth)')
ax.set_zlabel('Y (up)')

ax.set_box_aspect([1,1,1])

plt.show()


##########################################
##########################################

# hip center를 기준으로 바꾸기


# ---------------------------
# 1. 데이터
# ---------------------------
coords = np.array([
    [0.6300804, 0.3862279, -0.1800956],
    [0.4410107, 0.3599773, -0.1550435],

    [0.5893860, 0.4558804, -0.3774264],
    [0.3353628, 0.4086872, -0.4049845],

    [0.5149344, 0.4169530, -0.7744084],
    [0.3939202, 0.3853071, -0.8478600],

    [0.5569154, 0.5336347, -0.0010835],  # left hip
    [0.4362963, 0.5337196, 0.0008508],   # right hip

    [0.6532460, 0.6436756, -0.0020700],
    [0.3949564, 0.6579794, -0.0496367],

    [0.7307456, 0.7352291, 0.4672561],
    [0.3446633, 0.7684151, 0.3005700],
])

# ---------------------------
# 2. 연결
# ---------------------------
EDGES = [
    (0,2), (2,4),
    (1,3), (3,5),
    (0,1),
    (6,7),
    (0,6), (1,7),
    (6,8), (8,10),
    (7,9), (9,11),
]

# ---------------------------
# 3. hip center 계산
# ---------------------------
lhip = coords[6]
rhip = coords[7]
hip_center = (lhip + rhip) / 2

# ---------------------------
# 4. hip 기준 이동
# ---------------------------
coords_shifted = coords - hip_center

# ---------------------------
# 5. 시각화
# ---------------------------
fig = plt.figure(figsize=(12,6))

# -------- Original --------
ax1 = fig.add_subplot(121, projection='3d')

for i, j in EDGES:
    ax1.plot(
        [coords[i,0], coords[j,0]],
        [coords[i,2], coords[j,2]],
        [-coords[i,1], -coords[j,1]]
    )

ax1.scatter(coords[:,0], coords[:,2], -coords[:,1])

# (0,0,0) 표시
ax1.scatter(0, 0, 0, color='red', s=100, label='(0,0,0)')

ax1.set_title("Original")
ax1.legend()


# -------- After --------
ax2 = fig.add_subplot(122, projection='3d')

for i, j in EDGES:
    ax2.plot(
        [coords_shifted[i,0], coords_shifted[j,0]],
        [coords_shifted[i,2], coords_shifted[j,2]],
        [-coords_shifted[i,1], -coords_shifted[j,1]]
    )

ax2.scatter(
    coords_shifted[:,0],
    coords_shifted[:,2],
    -coords_shifted[:,1]
)

# (0,0,0) 표시 (여기는 hip 위치)
ax2.scatter(0, 0, 0, color='red', s=100, label='(0,0,0)')

ax2.set_title("After Hip Center Alignment")
ax2.legend()

# 보기 좋게
ax1.set_box_aspect([1,1,1])
ax2.set_box_aspect([1,1,1])

plt.show()

##########################################
##########################################

# 1. hip center로 바꾸기
# 2. 사용자 기준축으로 바꾸기


# ---------------------------
# 1. 데이터
# ---------------------------
coords = np.array([
    [0.6300804, 0.3862279, -0.1800956],
    [0.4410107, 0.3599773, -0.1550435],

    [0.5893860, 0.4558804, -0.3774264],
    [0.3353628, 0.4086872, -0.4049845],

    [0.5149344, 0.4169530, -0.7744084],
    [0.3939202, 0.3853071, -0.8478600],

    [0.5569154, 0.5336347, -0.0010835],  # left hip
    [0.4362963, 0.5337196, 0.0008508],   # right hip

    [0.6532460, 0.6436756, -0.0020700],
    [0.3949564, 0.6579794, -0.0496367],

    [0.7307456, 0.7352291, 0.4672561],
    [0.3446633, 0.7684151, 0.3005700],
])

EDGES = [
    (0,2), (2,4),
    (1,3), (3,5),
    (0,1),
    (6,7),
    (0,6), (1,7),
    (6,8), (8,10),
    (7,9), (9,11),
]

# ---------------------------
# 2. hip center 이동
# ---------------------------
lhip = coords[6]
rhip = coords[7]
hip_center = (lhip + rhip) / 2

coords_shifted = coords - hip_center

# ---------------------------
# 3. basis(기준축) 생성
# ---------------------------

# x축 (hip 방향)
x_axis = lhip - rhip
x_axis /= np.linalg.norm(x_axis)

# 방향 통일 (좌우 뒤집힘 방지)
if x_axis[0] < 0:
    x_axis = -x_axis

# y축 (몸 기준 → 위쪽 강제)
l_shoulder = coords[0]
r_shoulder = coords[1]
shoulder_center = (l_shoulder + r_shoulder) / 2

y_axis = shoulder_center - hip_center
y_axis /= np.linalg.norm(y_axis)

# 위쪽으로 강제
if y_axis[1] < 0:
    y_axis = -y_axis

# z축
z_axis = np.cross(x_axis, y_axis)
z_axis /= np.linalg.norm(z_axis)

# 앞뒤 방향 통일
if z_axis[2] < 0:
    z_axis = -z_axis

# 직교화
y_axis = np.cross(z_axis, x_axis)
y_axis /= np.linalg.norm(y_axis)

# 회전 행렬
R = np.stack([x_axis, y_axis, z_axis], axis=1)

# ---------------------------
# 4. basis 적용
# ---------------------------
coords_aligned = coords_shifted @ R

# ---------------------------
# 5. 시각화
# ---------------------------
fig = plt.figure(figsize=(18,6))

# -------- Original --------
ax1 = fig.add_subplot(131, projection='3d')
for i, j in EDGES:
    ax1.plot(
        [coords[i,0], coords[j,0]],
        [coords[i,2], coords[j,2]],
        [-coords[i,1], -coords[j,1]]
    )
ax1.scatter(coords[:,0], coords[:,2], -coords[:,1])
ax1.set_title("Original")

# -------- Hip Only --------
ax2 = fig.add_subplot(132, projection='3d')
for i, j in EDGES:
    ax2.plot(
        [coords_shifted[i,0], coords_shifted[j,0]],
        [coords_shifted[i,2], coords_shifted[j,2]],
        [-coords_shifted[i,1], -coords_shifted[j,1]]
    )
ax2.scatter(coords_shifted[:,0], coords_shifted[:,2], -coords_shifted[:,1])
ax2.set_title("Hip Center Only")

# -------- Basis --------
ax3 = fig.add_subplot(133, projection='3d')
for i, j in EDGES:
    ax3.plot(
        [coords_aligned[i,0], coords_aligned[j,0]],
        [coords_aligned[i,2], coords_aligned[j,2]],
        [-coords_aligned[i,1], -coords_aligned[j,1]]
    )
ax3.scatter(coords_aligned[:,0], coords_aligned[:,2], -coords_aligned[:,1])
ax3.set_title("Stable Basis Alignment")

for ax in [ax1, ax2, ax3]:
    ax.set_box_aspect([1,1,1])

plt.show()

##########################################
##########################################

# 1. hip center로 바꾸기
# 2. 사용자 기준축으로 바꾸기
# 위랑 동일하지만 원점이 어디있는지 빨간 점으로 표시함

import numpy as np
import matplotlib.pyplot as plt

# ---------------------------
# 1. 데이터
# ---------------------------
coords = np.array([
    [0.6300804, 0.3862279, -0.1800956],
    [0.4410107, 0.3599773, -0.1550435],

    [0.5893860, 0.4558804, -0.3774264],
    [0.3353628, 0.4086872, -0.4049845],

    [0.5149344, 0.4169530, -0.7744084],
    [0.3939202, 0.3853071, -0.8478600],

    [0.5569154, 0.5336347, -0.0010835],  # left hip
    [0.4362963, 0.5337196, 0.0008508],   # right hip

    [0.6532460, 0.6436756, -0.0020700],
    [0.3949564, 0.6579794, -0.0496367],

    [0.7307456, 0.7352291, 0.4672561],
    [0.3446633, 0.7684151, 0.3005700],
])

EDGES = [
    (0,2), (2,4),
    (1,3), (3,5),
    (0,1),
    (6,7),
    (0,6), (1,7),
    (6,8), (8,10),
    (7,9), (9,11),
]

# ---------------------------
# 2. hip center 이동
# ---------------------------
lhip = coords[6]
rhip = coords[7]
hip_center = (lhip + rhip) / 2
coords_shifted = coords - hip_center

# ---------------------------
# 3. basis 생성 (안정화 버전)
# ---------------------------
# x축
x_axis = lhip - rhip
x_axis /= np.linalg.norm(x_axis)
if x_axis[0] < 0:
    x_axis = -x_axis

# y축 (몸 기준 → 위 방향 강제)
l_shoulder = coords[0]
r_shoulder = coords[1]
shoulder_center = (l_shoulder + r_shoulder) / 2

y_axis = shoulder_center - hip_center
y_axis /= np.linalg.norm(y_axis)
if y_axis[1] < 0:
    y_axis = -y_axis

# z축
z_axis = np.cross(x_axis, y_axis)
z_axis /= np.linalg.norm(z_axis)
if z_axis[2] < 0:
    z_axis = -z_axis

# 직교화
y_axis = np.cross(z_axis, x_axis)
y_axis /= np.linalg.norm(y_axis)

# 회전 행렬
R = np.stack([x_axis, y_axis, z_axis], axis=1)

# ---------------------------
# 4. basis 적용
# ---------------------------
coords_aligned = coords_shifted @ R

# ---------------------------
# 5. 축 동일하게 맞추는 함수
# ---------------------------
def set_equal_axis(ax, data):
    x = data[:,0]
    y = data[:,2]
    z = -data[:,1]

    max_range = np.array([
        x.max()-x.min(),
        y.max()-y.min(),
        z.max()-z.min()
    ]).max() / 2.0

    mid_x = (x.max()+x.min()) / 2
    mid_y = (y.max()+y.min()) / 2
    mid_z = (z.max()+z.min()) / 2

    ax.set_xlim(mid_x - max_range, mid_x + max_range)
    ax.set_ylim(mid_y - max_range, mid_y + max_range)
    ax.set_zlim(mid_z - max_range, mid_z + max_range)

# ---------------------------
# 6. 시각화 함수
# ---------------------------
def draw(ax, data, title):
    for i, j in EDGES:
        ax.plot(
            [data[i,0], data[j,0]],
            [data[i,2], data[j,2]],
            [-data[i,1], -data[j,1]]
        )

    ax.scatter(
        data[:,0],
        data[:,2],
        -data[:,1]
    )

    # 원점 표시
    ax.scatter(0, 0, 0, color='red', s=100, label='origin')

    # 축 동일
    set_equal_axis(ax, data)
    ax.set_box_aspect([1,1,1])

    ax.set_title(title)
    ax.legend()

# ---------------------------
# 7. 실행
# ---------------------------
fig = plt.figure(figsize=(18,6))

ax1 = fig.add_subplot(131, projection='3d')
draw(ax1, coords, "Original")

ax2 = fig.add_subplot(132, projection='3d')
draw(ax2, coords_shifted, "Hip Center Only")

ax3 = fig.add_subplot(133, projection='3d')
draw(ax3, coords_aligned, "Stable Basis Alignment")

plt.show()


##########################################
##########################################
# 사람 기준축으로 바꾼 후 x,y,z 축을 표시해 제대로 바꿨는지 시각화


# ---------------------------
# 1. 데이터
# ---------------------------
coords = np.array([
    [0.6300804, 0.3862279, -0.1800956],
    [0.4410107, 0.3599773, -0.1550435],

    [0.5893860, 0.4558804, -0.3774264],
    [0.3353628, 0.4086872, -0.4049845],

    [0.5149344, 0.4169530, -0.7744084],
    [0.3939202, 0.3853071, -0.8478600],

    [0.5569154, 0.5336347, -0.0010835],  # left hip
    [0.4362963, 0.5337196, 0.0008508],   # right hip

    [0.6532460, 0.6436756, -0.0020700],
    [0.3949564, 0.6579794, -0.0496367],

    [0.7307456, 0.7352291, 0.4672561],
    [0.3446633, 0.7684151, 0.3005700],
])

EDGES = [
    (0,2), (2,4),
    (1,3), (3,5),
    (0,1),
    (6,7),
    (0,6), (1,7),
    (6,8), (8,10),
    (7,9), (9,11),
]

# ---------------------------
# 2. hip center 이동
# ---------------------------
lhip = coords[6]
rhip = coords[7]
hip_center = (lhip + rhip) / 2
coords_shifted = coords - hip_center

# ---------------------------
# 3. basis 생성
# ---------------------------
# x축 (hip 기준)
x_axis = lhip - rhip
x_axis /= np.linalg.norm(x_axis)
if x_axis[0] < 0:
    x_axis = -x_axis

# y축 (몸 위 방향)
l_shoulder = coords[0]
r_shoulder = coords[1]
shoulder_center = (l_shoulder + r_shoulder) / 2

y_axis = shoulder_center - hip_center
y_axis /= np.linalg.norm(y_axis)
if y_axis[1] < 0:
    y_axis = -y_axis

# z축 (앞 방향)
z_axis = np.cross(x_axis, y_axis)
z_axis /= np.linalg.norm(z_axis)
if z_axis[2] < 0:
    z_axis = -z_axis

# 직교화
y_axis = np.cross(z_axis, x_axis)
y_axis /= np.linalg.norm(y_axis)

# 회전 행렬
R = np.stack([x_axis, y_axis, z_axis], axis=1)

# ---------------------------
# 4. basis 적용
# ---------------------------
coords_aligned = coords_shifted @ R

# ---------------------------
# 5. 축 동일 함수
# ---------------------------
def set_equal_axis(ax, data):
    x = data[:,0]
    y = data[:,2]
    z = -data[:,1]

    max_range = np.array([
        x.max()-x.min(),
        y.max()-y.min(),
        z.max()-z.min()
    ]).max() / 2.0

    mid_x = (x.max()+x.min()) / 2
    mid_y = (y.max()+y.min()) / 2
    mid_z = (z.max()+z.min()) / 2

    ax.set_xlim(mid_x - max_range, mid_x + max_range)
    ax.set_ylim(mid_y - max_range, mid_y + max_range)
    ax.set_zlim(mid_z - max_range, mid_z + max_range)

# ---------------------------
# 6. 시각화 (basis + 축 표시)
# ---------------------------
fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')

# 스켈레톤
for i, j in EDGES:
    ax.plot(
        [coords_aligned[i,0], coords_aligned[j,0]],
        [coords_aligned[i,2], coords_aligned[j,2]],
        [-coords_aligned[i,1], -coords_aligned[j,1]]
    )

ax.scatter(
    coords_aligned[:,0],
    coords_aligned[:,2],
    -coords_aligned[:,1]
)

# ---------------------------
# 기준 좌표계 (축) 그리기
# ---------------------------
origin = np.array([0,0,0])
scale = 0.3  # 축 길이

# x축 (빨강)
ax.quiver(0,0,0,
          x_axis[0], x_axis[2], -x_axis[1],
          length=scale, color='red', label='x-axis')

# y축 (초록)
ax.quiver(0,0,0,
          y_axis[0], y_axis[2], -y_axis[1],
          length=scale, color='green', label='y-axis')

# z축 (파랑)
ax.quiver(0,0,0,
          z_axis[0], z_axis[2], -z_axis[1],
          length=scale, color='blue', label='z-axis')

# 원점
ax.scatter(0,0,0, color='black', s=100)

set_equal_axis(ax, coords_aligned)
ax.set_box_aspect([1,1,1])

ax.set_title("Basis Alignment + Axes")
ax.legend()

plt.show()