# -*- coding: utf-8 -*-
"""open_cv구현.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZA3YrYqmB3jtKawHlnlJmV_F4D1_5se
"""

# video_path: 비디오 한 개의 경로, yolo_model: 욜로 모델, metadata: 좌우유무 파일
def process_video(video_path, yolo_model, metadata=None):
  # 비디오 > 프레임 리스트로 바꿈
  frames = read_video(video_path)

  # roi된 프레임을 넣음
  roi_frames = []
  # 프레임 별 bat 각도 리스트
  bat_angels = []
  # 프레입 려 bat 위치 리스트
  bat_positions = []

  # 1. YOLO + ROI
  for frame in frames:

    # 사람 좌표, 배트 좌표, 배트 각도
    # --------------------------------
    # --------------------------------
    # !! yolo_inference 이 부분 구현 !!
    person_bbox, bat_bbox, bat_angle = yolo_inference(yolog_model, frame)

    # roi + 프레임 크기 통일
    roi = process_roi(frame, person_bbox, target_size=256, pad=20)

    # 배트 중심 좌표
    x1, y1, x2, y2 = bat_bbox
    bat_x = (x1 + x2) / 2
    bat_y = (y1 + y2) / 2

    roi_frames.append(roi)
    bat_angels.append(bat_angle)
    bat_positions.append((bat_x, bat_y))

  # 2. 프레임 수 통일(80)
  roi_frames = make_80_frames(roi_frames)
  bat_angles = make_80_frames(bat_angles)
  bat_positions = make_80_frames(bat_positions)

  # 3. 좌우 통일
  video_name = video_path.split('/')[-1]
  handness = metadata.get(video_name)
  is_left = (handness == 'left')

  if is_left:
    roi_frames, bat_angles, bat_positions = unify_left(roi_frames, bat_angles, bat_positions)

  # 4. MediaPipe
  all_landmarks = []

  for frame in roi_frames:
    # --------------------------------
    # --------------------------------
    # !! extract_pose 이 부분 구현 !!
    lm = extract_pose(frame)
    all_landmarks.append(lm)

  # 5. Feature 생성(최종 데이터)
  final_data = make_features(all_landmarks, bat_angles, bat_positions)

  return final_data