# -*- coding: utf-8 -*-
"""lstm_autoencoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFsKWF-Coor0_E5wk1uDNhSwfWAa-SbW
"""

import torch
import torch.nn as nn

class LSTMAutoEncoder(nn.Module):
    '''
    input_dim: feature 개수
    hidden_dim: LSTM 내부 상태 크기
    latent_dim: 압축된 벡터 크기
    num_layers: LSTM 층 개수
    '''
    def __init__(self, input_dim, hidden_dim=128, latent_dim=32, num_layers=2):
        # 부모 클래스 초기화
        super().__init__()

        self.hidden_dim = hidden_dim
        self.num_layers = num_layers

        #--------------------------------------------------

        # Encoder
        # 입력 시퀀스를 받아서 hidden state로 변환
        # (배치, 프레임수, 피처 수) → (배치, 프레임수, hidden_dim)
        self.encoder = nn.LSTM(
            input_dim,
            hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout = 0.2,
            # 양방향 LSTM: (B, T, D) → (B, T, hidden_dim * 2)
            bidirectional=True
        )

        #--------------------------------------------------

        # LSTM의 마지막 hidden state → latent vector로 압축
        # 요약된 스윙 정보
        # bidirectional이라 hidden_dim * 2
        # (B, hidden_dim*2) → (B, latent_dim)
        self.fc_enc = nn.Linear(hidden_dim * 2, latent_dim)


        #--------------------------------------------------

        # Decoder: 요약된 정보를 다시 시퀀스로 복원
        # latent vector → 다시 hidden space로 확장

        # latent vector z를 hidden state(h0) 크기로 변환
        self.fc_dec_h = nn.Linear(latent_dim, hidden_dim)

        # latent를 cell state(c0)로 변환
        self.fc_dec_c = nn.Linear(latent_dim, hidden_dim)

        self.decoder = nn.LSTM(
            input_size = hidden_dim + 1,  # +1: 시간 정보 추가
            hidden_size = hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout = 0.2
        )

        # 최종 출력 반환: 원래 feature 차원으로 변환
        self.output_layer = nn.Linear(hidden_dim, input_dim)

    #--------------------------------------------------

    # 입력을 latent vector로 변환하는 함수
    def encode(self, x):
        # x: (B, T, D)
        # self.encoder 반환값: output((B, T, hidden_dim * 2)), (h_n, c_n) 반환
        # out: 모든 timestep의 hidden 상태
        out, _ = self.encoder(x)

        # 전체 시퀀스 정보 반영하기 위해 평균: 전체 시퀀스를 하나의 벡터로 요약
        h_mean = out.mean(dim=1)  # (B, hidden_dim * 2)

        # 스윙 전체를 압축한 벡터
        z = self.fc_enc(h_mean)  # (B, latent_dim)

        # 압축된 벡터 반환
        return z

    #--------------------------------------------------

    # latent vector → 시퀀스로 복원
    def decode(self, z, seq_len):

        # 배치 크기 가져옴
        B = z.size(0)

        # latent → hidden으로 확장
        # z: latent vector, (B, latent_dim)
        h0 = self.fc_dec_h(z)  # (B, latent_dim) -> (B, hidden_dim)
        c0 = self.fc_dec_c(z)  # (B, hidden_dim)

        '''
        h0 (hidden state): 지금 상태가 어떤지
        c0 ((cell state)): 기억을 저장하는 공간

        입력은 아무 정보도 주지 않고
        초기 상태(h0)에 넣은 z만으로
        LSTM이 전체 시퀀스를 생성하게 하는 구조
        '''

        # (B, hidden_dim) -> (B, T, hidden_dim) 이렇게 바꿔야 함
        # unsqueeze(0): (B, hidden_dim) -> (1, B, hidden_dim)
        # repeat(self.num_layers, 1, 1): (1, B, hidden_dim) → (num_layers, B, hidden_dim)
        h0 = h0.unsqueeze(0).repeat(self.num_layers, 1, 1)
        c0 = c0.unsqueeze(0).repeat(self.num_layers, 1, 1)

        # 시간 정보 생성: 길이가 seq_len인 벡터 생성
        # 값: 0 ~ 1까지 균등하게 증가
        t = torch.linspace(0, 1, seq_len, device=z.device)
        # unsqueeze(0): (T,) → (1, T)
        # unsqueeze(-1): (1, T) → (1, T, 1)
        # repeat(B, 1, 1): 모든 데이터에 동일한 시간 정보 복사, (1, T, 1) → (B, T, 1)
        t = t.unsqueeze(0).unsqueeze(-1).repeat(B, 1, 1 )

        # latent 기반 입력 생성
        # 마지막 layer의 hidden state를 가져와서 전체 timestep 길이만큼 반복
        base_input = h0[-1].unsqueeze(1).repeat(1, seq_len, 1)

        # base_input: (B, T, hidden_dim) + t: (B, T, 1) -> 피처 차원에서 합침
        # inputs: (B, T, hidden_dim + 1)
        inputs = torch.cat([base_input, t], dim=2)

        # out: (B, T, hidden_dim)
        out, _ = self.decoder(inputs, (h0, c0))

        # 최종 출력: (B, T, input_dim)
        out = self.output_layer(out)

        return out

    #--------------------------------------------------

    def forward(self, x):
        z = self.encode(x)
        x_hat = self.decode(z, x.size(1))
        return x_hat