# -*- coding: utf-8 -*-
"""find_reference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFsKWF-Coor0_E5wk1uDNhSwfWAa-SbW
"""

import torch
import numpy as np


def find_nearest_real_swing(model, data):

    model.eval()

    device = next(model.parameters()).device

    latents = []

    # --------------------------------------------------
    # latent vector 추출
    # --------------------------------------------------

    with torch.no_grad():

        for x in data:

            x_tensor = torch.as_tensor(
                x,
                dtype=torch.float32
            ).unsqueeze(0).to(device)

            # latent vector
            z = model.encode(x_tensor)

            latents.append(
                z.squeeze(0)
            )

    # --------------------------------------------------
    # latent stack
    # shape: (N, latent_dim)
    # --------------------------------------------------

    latents = torch.stack(latents)

    # --------------------------------------------------
    # median latent
    # --------------------------------------------------

    z_median = torch.median(
        latents,
        dim=0
    ).values

    # --------------------------------------------------
    # distance 계산
    # --------------------------------------------------

    distances = torch.norm(
        latents - z_median,
        dim=1
    )

    # --------------------------------------------------
    # 가장 가까운 스윙 선택
    # --------------------------------------------------

    nearest_idx = torch.argmin(
        distances
    ).item()

    nearest_distance = distances[
        nearest_idx
    ].item()

    # --------------------------------------------------
    # 통계 출력
    # --------------------------------------------------

    print("nearest index:", nearest_idx)
    print("nearest distance:", nearest_distance)

    print("distance mean :", distances.mean().item())
    print("distance std  :", distances.std().item())
    print("distance min  :", distances.min().item())
    print("distance max  :", distances.max().item())

    # --------------------------------------------------
    # 기준 스윙 반환
    # --------------------------------------------------

    nearest_swing = data[nearest_idx]

    return (
        nearest_swing,
        nearest_idx,
        nearest_distance,
        distances.cpu().numpy()
    )