# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFsKWF-Coor0_E5wk1uDNhSwfWAa-SbW
"""

import os
import torch

from torch.utils.data import DataLoader

from dataset import SwingDataset
from models.lstm_autoencoder import LSTMAutoEncoder
from train import train_model
from find_reference import find_nearest_real_swing


def main():

    # --------------------------------------------------
    # dataset path
    # --------------------------------------------------

    folder_path = "./feature_dtw_aligned"

    # --------------------------------------------------
    # dataset
    # --------------------------------------------------

    dataset = SwingDataset(folder_path)

    dataloader = DataLoader(
        dataset,
        batch_size=32,
        shuffle=True
    )

    # --------------------------------------------------
    # input_dim 자동 추출
    # --------------------------------------------------

    sample = dataset[0]

    # shape: (T, D)
    input_dim = sample.shape[1]

    print("input_dim:", input_dim)

    # --------------------------------------------------
    # model 생성
    # --------------------------------------------------

    model = LSTMAutoEncoder(
        input_dim=input_dim,
        hidden_dim=128,
        latent_dim=32,
        num_layers=2
    )

    # --------------------------------------------------
    # device 설정
    # --------------------------------------------------

    device = "cuda" if torch.cuda.is_available() else "cpu"

    print("device:", device)

    # --------------------------------------------------
    # model train
    # --------------------------------------------------

    model = train_model(
        model,
        dataloader,
        epochs=50, # 1200번 수행
        device=device
    )

    # --------------------------------------------------
    # checkpoint 폴더 생성
    # --------------------------------------------------

    os.makedirs("checkpoints", exist_ok=True)

    # --------------------------------------------------
    # model save
    # --------------------------------------------------

    save_path = "checkpoints/lstm_model.pth"

    torch.save(
        model.state_dict(),
        save_path
    )

    print("모델 저장 완료!")
    print("저장 경로:", save_path)

    # --------------------------------------------------
    # train data numpy 변환
    # --------------------------------------------------

    train_data = []

    for x in dataset:
        train_data.append(x.numpy())

    # --------------------------------------------------
    # 기준 스윙 선정
    # --------------------------------------------------

    reference_real_swing, idx, nearest_distance, distances = (
        find_nearest_real_swing(
            model,
            train_data
        )
    )

    # --------------------------------------------------
    # 결과 출력
    # --------------------------------------------------

    print("reference swing shape:")
    print(reference_real_swing.shape)

    print("nearest index:")
    print(idx)

    print("nearest distance:")
    print(nearest_distance)

    # --------------------------------------------------
    # 기준 스윙 파일 경로
    # --------------------------------------------------

    nearest_file = dataset.files[idx]

    print("nearest file:")
    print(nearest_file)

    # --------------------------------------------------
    # 기준 스윙 저장
    # --------------------------------------------------

    npy_save_path = "checkpoints/reference_swing.npy"

    os.makedirs("checkpoints", exist_ok=True)

    import numpy as np

    np.save(
        npy_save_path,
        reference_real_swing
    )

    print("reference swing saved!")
    print("save path:", npy_save_path)


# --------------------------------------------------
# main 실행
# --------------------------------------------------

if __name__ == "__main__":
    main()