# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFsKWF-Coor0_E5wk1uDNhSwfWAa-SbW
"""

import matplotlib.pyplot as plt

# model: LSTM Autoencoder
# dataloader: 배치 단위 데이터
def train_model(model, dataloader, epochs=50, lr=1e-3, device="cuda"):
    model.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.MSELoss()

    for epoch in range(epochs):
        model.train()

        total_loss = 0

        for batch in dataloader:
            x = batch.to(device)  # (B, T, D)

            optimizer.zero_grad()

            x_hat = model(x)
            loss = criterion(x_hat, x)

            loss.backward()

            # gradient 너무 크면 클립
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()

            total_loss += loss.item()

        avg_loss = total_loss / len(dataloader)

        print(f"Epoch {epoch+1}, Loss: {avg_loss:.4f}")

        # -----------------------------------
        # 10 epoch마다 reconstruction 확인
        # -----------------------------------
        if (epoch + 1) % 10 == 0:

          with torch.no_grad():

            original = x[0].cpu().numpy()
            reconstructed = x_hat[0].cpu().numpy()

            plt.figure(figsize=(10, 4))

            # 첫 번째 feature trajectory 비교
            plt.plot(original[:, 0], label="Original")
            plt.plot(reconstructed[:, 0], label="Reconstructed")

            plt.title(f"Epoch {epoch+1}")
            plt.xlabel("Frame")
            plt.ylabel("Feature Value")

            plt.legend()
            plt.show()

    return model